openapi: 3.1.0
info:
  title: Simple API
  version: 1.0.0
paths:
  /test:
    get:
      operationId: testGet
      summary: Test endpoint
      responses:
        '200':
          description: Success
